version: '3'
services:
  osmium-tool:
    image: quay.io/azavea/osmium-tool:latest
    build:
      context: docker/osmium-tool
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  metastore-database:
    image: postgres:10.3
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
  metastore-init:
    image: quay.io/azavea/hive:latest
    command: bash -c "/opt/poke.sh"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    links:
      - metastore-database:database
  metastore-info:
    image: quay.io/azavea/hive:latest
    command: bash -c "/opt/peek.sh"
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    links:
      - metastore-database:database
  hive:
    image: quay.io/azavea/hive:latest
    command: /opt/start-hiveserver2.sh
    build:
      context: ./docker/hive
      dockerfile: Dockerfile
    links:
      - metastore-database:database
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "10000:10000"
