version: '3'
services:
  osmium-tool:
    image: quay.io/azavea/osmium-tool:latest
    build:
      context: docker/osmium-tool
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
  metastore-database:
    image: postgres:10.3
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=metastore
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=hive
    ports:
      - "5432:5432"
  metastore-init:
    image: quay.io/azavea/hive:latest
    command: bash -c '/opt/start-services.sh && schematool -dbType postgres -initSchema && echo "ALTER TABLE \"TBLS\" ALTER COLUMN \"IS_REWRITE_ENABLED\" DROP NOT NULL;" | PGPASSWORD=hive psql -h metastore-database -U hive -d metastore'
    links:
      - metastore-database:database
  metastore-info:
    image: quay.io/azavea/hive:latest
    command: bash -c "/opt/start-services.sh ; schematool -dbType postgres -info"
    links:
      - metastore-database:database
  hive:
    image: quay.io/azavea/hive:latest
    build:
      context: ./docker/hive
      dockerfile: Dockerfile
    links:
      - metastore-database:database
    ports:
      - "10000:10000"
